ALTER TABLE sys_company_settings
    ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587,
    ADD COLUMN IF NOT EXISTS smtp_secure VARCHAR(8) NOT NULL DEFAULT 'tls',
    ADD COLUMN IF NOT EXISTS smtp_username VARCHAR(160) NULL,
    ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS smtp_from_email VARCHAR(160) NULL,
    ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(160) NULL;
