ALTER TABLE sys_company_settings
    ADD COLUMN IF NOT EXISTS wa_provider VARCHAR(16) NOT NULL DEFAULT 'cloud',
    ADD COLUMN IF NOT EXISTS wa_phone_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS wa_access_token VARCHAR(512) NULL,
    ADD COLUMN IF NOT EXISTS wa_api_version VARCHAR(16) NOT NULL DEFAULT 'v20.0',
    ADD COLUMN IF NOT EXISTS wa_default_country VARCHAR(8) NULL,
    ADD COLUMN IF NOT EXISTS wa_bridge_url VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS wa_bridge_token VARCHAR(255) NULL;
