CREATE TABLE IF NOT EXISTS hr_employee (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    emp_code VARCHAR(40) NULL,
    name_ar VARCHAR(160) NOT NULL,
    national_id VARCHAR(40) NULL,
    phone VARCHAR(40) NULL,
    email VARCHAR(160) NULL,
    job_title VARCHAR(120) NULL,
    department VARCHAR(120) NULL,
    hire_date DATE NULL,
    base_salary DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    allowances DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    social_security_no VARCHAR(60) NULL,
    bank_name VARCHAR(120) NULL,
    bank_account VARCHAR(60) NULL,
    notes TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_hr_employee_code (emp_code),
    KEY idx_hr_employee_active (is_active),
    KEY idx_hr_employee_dept (department)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_salary (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    employee_id INT UNSIGNED NOT NULL,
    pay_year SMALLINT UNSIGNED NOT NULL,
    pay_month TINYINT UNSIGNED NOT NULL,
    base_salary DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    allowances DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    overtime DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    bonus DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    deductions DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    social_security_emp DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    income_tax DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    net_salary DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    pay_date DATE NULL,
    notes TEXT NULL,
    is_posted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_hr_salary_period (employee_id, pay_year, pay_month),
    KEY idx_hr_salary_period (pay_year, pay_month),
    CONSTRAINT fk_hr_salary_emp FOREIGN KEY (employee_id) REFERENCES hr_employee(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_social_security (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    employee_id INT UNSIGNED NOT NULL,
    pay_year SMALLINT UNSIGNED NOT NULL,
    pay_month TINYINT UNSIGNED NOT NULL,
    base_amount DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    employee_share DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    employer_share DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    total_share DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    pay_date DATE NULL,
    reference_no VARCHAR(80) NULL,
    notes TEXT NULL,
    is_posted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_hr_ssec_period (employee_id, pay_year, pay_month),
    KEY idx_hr_ssec_period (pay_year, pay_month),
    CONSTRAINT fk_hr_ssec_emp FOREIGN KEY (employee_id) REFERENCES hr_employee(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
