CREATE TABLE IF NOT EXISTS sys_license (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  license_key TEXT NOT NULL,
  fingerprint_hash CHAR(64) NOT NULL,
  issued_to VARCHAR(190) NULL,
  expires_on DATE NULL,
  payload_json LONGTEXT NULL,
  activated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
