-- دعم حتى 10 خانات عشرية في مبالغ الفواتير والمرتجعات
SET NAMES utf8mb4;

ALTER TABLE sal_invoice
  MODIFY subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY total DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE sal_invoice_line
  MODIFY unit_price DECIMAL(18,10) NOT NULL,
  MODIFY line_total DECIMAL(18,10) NOT NULL,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY line_gross DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY discount_amount DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE pur_invoice
  MODIFY subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY total DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE pur_invoice_line
  MODIFY unit_price DECIMAL(18,10) NOT NULL,
  MODIFY line_total DECIMAL(18,10) NOT NULL,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY line_gross DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY discount_amount DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE sal_return
  MODIFY subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY total DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE sal_return_line
  MODIFY unit_price DECIMAL(18,10) NOT NULL,
  MODIFY line_subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY line_gross DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE pur_return
  MODIFY subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY total DECIMAL(18,10) NOT NULL DEFAULT 0;

ALTER TABLE pur_return_line
  MODIFY unit_price DECIMAL(18,10) NOT NULL,
  MODIFY line_subtotal DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY tax_amount DECIMAL(18,10) NOT NULL DEFAULT 0,
  MODIFY line_gross DECIMAL(18,10) NOT NULL DEFAULT 0;
