<?php
declare(strict_types=1);

/**
 * شريط الأزرار الموحّد (Master) — يظهر أعلى الشاشات.
 *
 * لكل زر:
 * - screens: قائمة أكواد الشاشات (r) التي يظهر فيها الزر فقط.
 * - permission: صلاحية اختيارية (مثل sales_send_einvoice).
 *
 * بدون screens يظهر الزر في كل الشاشات (يُستخدم لـ «خروج» فقط).
 * السلوك يُربط في JavaScript عبر حدث master-toolbar.
 */
return [
    'exit_route' => 'dashboard',
    'buttons' => [
        [
            'action' => 'search',
            'label' => 'بحث',
            'variant' => 'secondary',
            'title' => 'بحث بالرقم في المستند الحالي أو في قائمة الترحيل',
            'screens' => [
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_returns',
                'purchase_returns_list',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'item_sale_price_adjust',
                'hr_employees',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_social_security_rates',
                'hr_income_tax_settings',
                'sales_invoice_gps',
                'user_gps_locations',
            ],
        ],
        [
            'action' => 'new',
            'label' => 'جديد',
            'variant' => 'secondary',
            'title' => 'سجل جديد',
            'screens' => ['users', 'groups', 'hr_employees', 'hr_departments', 'hr_nationalities', 'hr_job_titles', 'hr_payroll_components', 'hr_salary_banks', 'hr_employee_bank_link', 'hr_salaries', 'hr_employee_advances', 'hr_monthly_payroll_adjustments', 'hr_social_security_rates', 'hr_income_tax_settings', 'inventory_stocktake'],
        ],
        [
            'action' => 'save',
            'label' => 'حفظ',
            'variant' => 'primary',
            'title' => 'حفظ المستند الحالي',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'cash_payment',
                'sales_returns',
                'purchase_invoices',
                'purchase_returns',
                'tax_rates_settings',
                'users',
                'groups',
                'permissions',
                'debit_notes',
                'credit_notes',
                'journal_voucher',
                'account_mapping',
                'item_sale_price_adjust',
                'inv_movement_types_settings',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_social_security_rates',
                'hr_income_tax_settings',
            ],
        ],
        [
            'action' => 'post',
            'label' => 'ترحيل',
            'variant' => 'secondary',
            'title' => 'ترحيل المستند (بيع: صرف + عميل — مرتجع بيع: عميل — شراء: إدخال + ذمة مورد — مردود شراء: مخزون + ذمة)',
            'screens' => [
                'item_sale_price_adjust',
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_returns',
                'purchase_returns_list',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
            ],
            'permission_by_screen' => [
                'item_sale_price_adjust' => 'action_post_item_sale_price_adjust',
                'warehouse_moves' => 'action_post_warehouse_move',
                'sales_invoices' => 'action_post_sales_invoice',
                'sales_invoices_list' => 'action_post_sales_invoice',
                'sales_delivery' => 'action_post_sales_delivery',
                'cash_receipt' => 'action_post_cash_receipt',
                'cash_receipts_list' => 'action_post_cash_receipt',
                'cash_payment' => 'action_post_cash_payment',
                'cash_payments_list' => 'action_post_cash_payment',
                'sales_returns' => 'action_post_sales_return',
                'sales_returns_list' => 'action_post_sales_return',
                'purchase_invoices' => 'action_post_purchase_invoice',
                'purchase_invoices_list' => 'action_post_purchase_invoice',
                'purchase_returns' => 'action_post_purchase_return',
                'purchase_returns_list' => 'action_post_purchase_return',
                'journal_voucher' => 'action_post_journal_voucher',
            ],
        ],
        [
            'action' => 'unpost',
            'label' => 'فك الترحيل',
            'variant' => 'secondary',
            'title' => 'فك ترحيل السند (يلغي الأثر على القيود المحاسبية وأرصدة المستودعات ويعيده مسودة)',
            'screens' => ['cash_receipt', 'cash_payment', 'journal_voucher', 'sales_invoices', 'sales_delivery', 'sales_returns', 'purchase_invoices', 'purchase_returns', 'warehouse_moves', 'inventory_stocktake', 'hr_employees'],
            'permission_by_screen' => [
                'sales_invoices' => 'action_unpost_sales_invoice',
                'sales_delivery' => 'action_unpost_sales_delivery',
                'sales_returns' => 'action_unpost_sales_return',
                'purchase_invoices' => 'action_unpost_purchase_invoice',
                'purchase_returns' => 'action_unpost_purchase_return',
                'cash_receipt' => 'action_unpost_cash_receipt',
                'cash_payment' => 'action_unpost_cash_payment',
                'journal_voucher' => 'action_unpost_journal_voucher',
                'warehouse_moves' => 'action_unpost_warehouse_move',
                'inventory_stocktake' => 'action_unpost_inventory_stocktake',
            ],
        ],
        [
            'action' => 'payroll_calculate',
            'label' => 'احتساب الرواتب',
            'variant' => 'primary',
            'title' => 'احتساب رواتب الموظفين المحددين لهذا الشهر',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_cancel_calc',
            'label' => 'إلغاء الاحتساب',
            'variant' => 'secondary',
            'title' => 'إلغاء احتساب الموظفين المحددين (محتسب فقط)',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_post',
            'label' => 'ترحيل الرواتب',
            'variant' => 'primary',
            'title' => 'ترحيل جميع القيود المحتسبة لهذا الشهر',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_unpost',
            'label' => 'فك الترحيل',
            'variant' => 'secondary',
            'title' => 'فك ترحيل رواتب الشهر (يلغي الاحتساب بالكامل)',
            'screens' => ['hr_payroll_posting'],
            'permission' => 'action_unpost_payroll',
        ],
        [
            'action' => 'print_slip',
            'label' => 'قسيمة الراتب',
            'variant' => 'secondary',
            'title' => 'طباعة قسيمة الراتب للقيد المحدد',
            'screens' => ['hr_salaries', 'hr_payroll_posting'],
        ],
        [
            'action' => 'print',
            'label' => 'طباعة',
            'variant' => 'secondary',
            'title' => 'طباعة المستند',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'purchase_invoices',
                'purchase_returns',
                'report_sales',
                'report_sales_between_dates',
                'report_purchases',
                'report_purchases_by_item',
                'report_sales_by_rep',
                'report_sales_by_item',
                'report_sales_returns',
                'report_sales_returns_totals',
                'report_purchase_returns',
                'report_sales_qty_extra',
                'report_customers',
                'report_hr_employees',
                'report_chart_of_accounts',
                'report_party_statement',
                'report_customer_statement',
                'report_supplier_statement',
                'report_receivables',
                'report_receivables_aging',
                'report_incoming_checks',
                'report_outgoing_checks',
                'report_supplier_payables',
                'report_vouchers',
                'item_stock_movements',
                'warehouse_moves',
                'inventory_stocktake',
                'report_warehouse_items',
                'report_warehouse_zero_qty',
                'report_warehouse_negative_qty',
                'report_warehouse_financial',
                'report_warehouse_moves',
                'report_trial_balance',
                'report_trial_balance_detailed',
                'report_general_ledger',
                'report_account_statement',
                'report_income_statement',
                'report_income_statement_comprehensive',
                'report_tax_declaration',
                'report_tax_ar3',
                'report_vat_net_payable',
                'report_balance_sheet',
                'hr_payroll_dept_report',
                'hr_payroll_ss_report',
                'hr_payroll_slip_report',
                'journal_entries',
                'journal_voucher',
                'sales_invoice_gps',
                'user_gps_locations',
            ],
        ],
        [
            'action' => 'pdf',
            'label' => 'PDF',
            'variant' => 'secondary',
            'title' => 'تحميل PDF',
            'screens' => ['sales_invoices', 'sales_delivery', 'sales_returns', 'purchase_invoices', 'purchase_returns', 'warehouse_moves', 'inventory_stocktake', 'report_sales', 'report_sales_between_dates', 'report_purchases', 'report_purchases_by_item', 'report_sales_by_rep', 'report_sales_by_item', 'report_sales_returns', 'report_sales_returns_totals', 'report_sales_qty_extra', 'report_customers', 'report_hr_employees', 'report_vouchers', 'report_incoming_checks', 'report_outgoing_checks', 'report_receivables', 'report_receivables_aging', 'report_supplier_payables', 'item_stock_movements', 'report_warehouse_items', 'report_warehouse_zero_qty', 'report_warehouse_negative_qty', 'report_warehouse_financial', 'report_warehouse_moves', 'report_trial_balance', 'report_trial_balance_detailed', 'report_general_ledger', 'report_account_statement', 'report_income_statement', 'report_income_statement_comprehensive', 'report_tax_declaration', 'report_tax_ar3', 'report_vat_net_payable', 'report_balance_sheet', 'hr_payroll_ss_report'],
        ],
        [
            'action' => 'excel',
            'label' => 'Excel',
            'variant' => 'secondary',
            'title' => 'تصدير Excel',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'purchase_invoices',
                'report_sales',
                'report_sales_between_dates',
                'report_purchases',
                'report_purchases_by_item',
                'report_sales_by_rep',
                'report_sales_by_item',
                'report_sales_returns',
                'report_sales_returns_totals',
                'report_purchase_returns',
                'report_sales_qty_extra',
                'report_customers',
                'report_hr_employees',
                'report_chart_of_accounts',
                'report_party_statement',
                'report_customer_statement',
                'report_supplier_statement',
                'report_receivables',
                'report_receivables_aging',
                'report_incoming_checks',
                'report_outgoing_checks',
                'report_supplier_payables',
                'report_vouchers',
                'item_stock_movements',
                'warehouse_moves',
                'inventory_stocktake',
                'report_warehouse_items',
                'report_warehouse_zero_qty',
                'report_warehouse_negative_qty',
                'report_warehouse_financial',
                'report_warehouse_moves',
                'report_trial_balance',
                'report_trial_balance_detailed',
                'report_general_ledger',
                'report_account_statement',
                'report_income_statement',
                'report_income_statement_comprehensive',
                'report_tax_declaration',
                'report_tax_ar3',
                'report_vat_net_payable',
                'report_balance_sheet',
                'hr_payroll_ss_report',
            ],
        ],
        [
            'action' => 'send_einvoice',
            'label' => 'إرسال للفوترة',
            'variant' => 'secondary',
            'title' => 'إرسال الفاتورة إلى نظام الفوترة الأردني',
            'screens' => ['sales_invoices'],
            'permission' => 'sales_send_einvoice',
        ],
        [
            'action' => 'send_email',
            'label' => 'Send Email',
            'variant' => 'secondary',
            'title' => 'إرسال المستند كـ PDF عبر البريد الإلكتروني',
            'screens' => [
                'sales_invoices',
                'purchase_invoices',
                'sales_returns',
                'purchase_returns',
            ],
        ],
        [
            'action' => 'send_return_einvoice',
            'label' => 'إرجاع للفوترة',
            'variant' => 'secondary',
            'title' => 'إرسال إشعار دائن (إرجاع) للفاتورة في نظام الفوترة الأردني',
            'screens' => ['sales_returns'],
            'permission' => 'sales_send_einvoice',
        ],
        [
            'action' => 'delete',
            'label' => 'حذف',
            'variant' => 'danger',
            'title' => 'مسح أو حذف المستند',
            'screens' => [
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_returns',
                'purchase_returns_list',
                'debit_notes',
                'credit_notes',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_social_security_rates',
                'hr_income_tax_settings',
            ],
            'permission_by_screen' => [
                'sales_invoices' => 'action_delete_sales_invoice',
                'sales_invoices_list' => 'action_delete_sales_invoice',
                'sales_delivery' => 'action_delete_sales_delivery',
                'cash_receipt' => 'action_delete_cash_receipt',
                'cash_receipts_list' => 'action_delete_cash_receipt',
                'cash_payment' => 'action_delete_cash_payment',
                'cash_payments_list' => 'action_delete_cash_payment',
                'sales_returns' => 'action_delete_sales_return',
                'sales_returns_list' => 'action_delete_sales_return',
                'purchase_invoices' => 'action_delete_purchase_invoice',
                'purchase_invoices_list' => 'action_delete_purchase_invoice',
                'purchase_returns' => 'action_delete_purchase_return',
                'purchase_returns_list' => 'action_delete_purchase_return',
                'debit_notes' => 'action_delete_debit_note',
                'credit_notes' => 'action_delete_credit_note',
                'journal_voucher' => 'action_delete_journal_voucher',
                'warehouse_moves' => 'action_delete_warehouse_move',
                'inventory_stocktake' => 'action_delete_inventory_stocktake',
            ],
        ],
        [
            'action' => 'exit',
            'label' => 'خروج',
            'variant' => 'secondary',
            'title' => 'العودة إلى قائمة الأيقونات أو لوحة التحكم',
            'display' => 'icon',
        ],
    ],
];
