<?php
declare(strict_types=1);

/**
 * شريط الأزرار الموحّد (Master) — يظهر أعلى الشاشات.
 *
 * لكل زر:
 * - screens: قائمة أكواد الشاشات (r) التي يظهر فيها الزر فقط.
 * - permission: صلاحية اختيارية (مثل sales_send_einvoice).
 *
 * بدون screens يظهر الزر في كل الشاشات (يُستخدم لـ «خروج» فقط).
 * السلوك يُربط في JavaScript عبر حدث master-toolbar.
 */
return [
    'exit_route' => 'dashboard',
    'buttons' => [
        [
            'action' => 'search',
            'label' => 'بحث',
            'variant' => 'secondary',
            'title' => 'بحث بالرقم في المستند الحالي أو في قائمة الترحيل',
            'screens' => [
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_orders',
                'purchase_orders_list',
                'purchase_returns',
                'purchase_returns_list',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'item_sale_price_adjust',
                'hr_employees',
                'hr_employee_attendance',
                'hr_attendance_sync_server',
                'hr_attendance_sync_local',
                'hr_attendance_settings',
                'hr_employee_schedule',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_employee_overtime',
                'hr_overtime_settings',
                'hr_social_security_rates',
                'hr_income_tax_settings',
                'sales_invoice_gps',
                'user_gps_locations',
                'user_gps_tracker',
            ],
        ],
        [
            'action' => 'new',
            'label' => 'جديد',
            'variant' => 'secondary',
            'title' => 'سجل جديد',
            'screens' => ['users', 'groups', 'hr_employees', 'hr_employee_attendance', 'hr_attendance_settings', 'hr_employee_schedule', 'hr_departments', 'hr_nationalities', 'hr_job_titles', 'hr_payroll_components', 'hr_salary_banks', 'hr_employee_bank_link', 'hr_salaries', 'hr_employee_advances', 'hr_monthly_payroll_adjustments', 'hr_employee_overtime', 'hr_overtime_settings', 'hr_social_security_rates', 'hr_income_tax_settings', 'inventory_stocktake'],
        ],
        [
            'action' => 'save',
            'label' => 'حفظ',
            'variant' => 'primary',
            'title' => 'حفظ المستند الحالي (F10)',
            'shortcut' => 'F10',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'cash_payment',
                'sales_returns',
                'purchase_invoices',
                'purchase_orders',
                'purchase_returns',
                'settings',
                'dashboard_accounts_settings',
                'tax_rates_settings',
                'einvoice_settings',
                'gps_tracking_settings',
                'system_error_log',
                'open_sessions',
                'users',
                'groups',
                'permissions',
                'debit_notes',
                'credit_notes',
                'journal_voucher',
                'account_mapping',
                'acc_period_close',
                'acc_year_close',
                'acc_opening_balance',
                'item_sale_price_adjust',
                'inv_movement_types_settings',
                'items',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
                'hr_employee_attendance',
                'hr_attendance_sync_server',
                'hr_attendance_sync_local',
                'hr_attendance_settings',
                'hr_employee_schedule',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_employee_overtime',
                'hr_overtime_settings',
                'hr_social_security_rates',
                'hr_income_tax_settings',
                'sales_customer_orders_approve',
                'sales_customer_order_entry',
                'sales_customer_order_entry_approve',
            ],
        ],
        [
            'action' => 'approve',
            'label' => 'اعتماد',
            'variant' => 'secondary',
            'title' => 'اعتماد طلب الشراء بعد الحفظ',
            'screens' => [
                'sales_customer_orders_approve',
                'sales_customer_order_entry',
                'sales_customer_order_entry_approve',
            ],
            'permission_by_screen' => [
                'sales_customer_orders_approve' => 'action_approve_customer_order',
                'sales_customer_order_entry' => 'action_approve_customer_order',
                'sales_customer_order_entry_approve' => 'action_approve_customer_order',
            ],
        ],
        [
            'action' => 'unapprove',
            'label' => 'فك الاعتماد',
            'variant' => 'secondary',
            'title' => 'فك اعتماد طلب الشراء وإعادته للمسودات',
            'screens' => [
                'sales_customer_orders_approved',
            ],
            'permission_by_screen' => [
                'sales_customer_orders_approved' => 'action_unapprove_customer_order',
            ],
        ],
        [
            'action' => 'post',
            'label' => 'ترحيل',
            'variant' => 'secondary',
            'title' => 'ترحيل المستند (بيع: صرف + عميل — مرتجع بيع: عميل — شراء: إدخال + ذمة مورد — مردود شراء: مخزون + ذمة)',
            'screens' => [
                'item_sale_price_adjust',
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_orders',
                'purchase_orders_list',
                'purchase_returns',
                'purchase_returns_list',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
                'hr_employee_attendance',
                'hr_attendance_sync_server',
                'hr_attendance_sync_local',
                'hr_employee_departures',
                'hr_employee_leaves',
                'hr_employee_advances',
            ],
            'permission_by_screen' => [
                'item_sale_price_adjust' => 'action_post_item_sale_price_adjust',
                'warehouse_moves' => 'action_post_warehouse_move',
                'hr_employee_advances' => 'action_post_employee_advance',
                'hr_employee_departures' => 'action_post_employee_departure',
                'hr_employee_leaves' => 'action_post_employee_leave',
                'sales_invoices' => 'action_post_sales_invoice',
                'sales_invoices_list' => 'action_post_sales_invoice',
                'sales_delivery' => 'action_post_sales_delivery',
                'cash_receipt' => 'action_post_cash_receipt',
                'cash_receipts_list' => 'action_post_cash_receipt',
                'cash_payment' => 'action_post_cash_payment',
                'cash_payments_list' => 'action_post_cash_payment',
                'sales_returns' => 'action_post_sales_return',
                'sales_returns_list' => 'action_post_sales_return',
                'purchase_invoices' => 'action_post_purchase_invoice',
                'purchase_invoices_list' => 'action_post_purchase_invoice',
                'purchase_orders' => 'action_approve_purchase_order',
                'purchase_orders_list' => 'action_approve_purchase_order',
                'purchase_returns' => 'action_post_purchase_return',
                'purchase_returns_list' => 'action_post_purchase_return',
                'journal_voucher' => 'action_post_journal_voucher',
            ],
        ],
        [
            'action' => 'edit',
            'label' => 'تعديل',
            'variant' => 'secondary',
            'title' => 'تعديل سند مرحّل بعد التحقق بكلمة المرور (فك الترحيل ثم التعديل وإعادة الترحيل)',
            'screens' => ['journal_voucher', 'cash_receipt', 'cash_payment'],
            'permission_by_screen' => [
                'journal_voucher' => 'action_edit_journal_voucher',
                'cash_receipt' => 'action_edit_cash_receipt',
                'cash_payment' => 'action_edit_cash_payment',
            ],
        ],
        [
            'action' => 'archive',
            'label' => 'أرشيف',
            'variant' => 'secondary',
            'title' => 'مرفقات المستند — رفع قبل الترحيل، أو عرض فقط بعد الترحيل',
            'screens' => [
                'journal_voucher',
                'cash_receipt',
                'cash_payment',
                'sales_invoices',
                'purchase_invoices',
                'sales_delivery',
                'sales_returns',
                'purchase_returns',
                'warehouse_moves',
            ],
            'permission_by_screen' => [
                'journal_voucher' => 'action_archive_journal_voucher',
                'cash_receipt' => 'action_archive_cash_receipt',
                'cash_payment' => 'action_archive_cash_payment',
                'sales_invoices' => 'action_archive_sales_invoice',
                'purchase_invoices' => 'action_archive_purchase_invoice',
                'sales_delivery' => 'action_archive_sales_delivery',
                'sales_returns' => 'action_archive_sales_return',
                'purchase_returns' => 'action_archive_purchase_return',
                'warehouse_moves' => 'action_archive_warehouse_move',
            ],
        ],
        [
            'action' => 'unpost',
            'label' => 'فك الترحيل',
            'variant' => 'secondary',
            'title' => 'فك ترحيل السند (يلغي الأثر على القيود المحاسبية وأرصدة المستودعات ويعيده مسودة)',
            'screens' => ['cash_receipt', 'cash_payment', 'journal_voucher', 'sales_invoices', 'sales_delivery', 'sales_returns', 'purchase_invoices', 'purchase_orders', 'purchase_returns', 'warehouse_moves', 'inventory_stocktake', 'hr_employees', 'hr_employee_attendance', 'hr_employee_departures', 'hr_employee_leaves', 'hr_employee_advances', 'acc_opening_balance'],
            'permission_by_screen' => [
                'hr_employee_advances' => 'action_unpost_employee_advance',
                'hr_employee_departures' => 'action_unpost_employee_departure',
                'hr_employee_leaves' => 'action_unpost_employee_leave',
                'sales_invoices' => 'action_unpost_sales_invoice',
                'sales_delivery' => 'action_unpost_sales_delivery',
                'sales_returns' => 'action_unpost_sales_return',
                'purchase_invoices' => 'action_unpost_purchase_invoice',
                'purchase_orders' => 'action_unapprove_purchase_order',
                'purchase_returns' => 'action_unpost_purchase_return',
                'cash_receipt' => 'action_unpost_cash_receipt',
                'cash_payment' => 'action_unpost_cash_payment',
                'journal_voucher' => 'action_unpost_journal_voucher',
                'warehouse_moves' => 'action_unpost_warehouse_move',
                'inventory_stocktake' => 'action_unpost_inventory_stocktake',
            ],
        ],
        [
            'action' => 'cancel_voucher',
            'label' => 'إلغاء السند',
            'variant' => 'danger',
            'title' => 'إلغاء السند المرحّل (يبقى برقم التسلسل ويُلغى أثره المحاسبي)',
            'screens' => ['cash_receipt', 'cash_payment', 'journal_voucher'],
            'permission_by_screen' => [
                'cash_receipt' => 'action_cancel_cash_receipt',
                'cash_payment' => 'action_cancel_cash_payment',
                'journal_voucher' => 'action_cancel_journal_voucher',
            ],
        ],
        [
            'action' => 'payroll_calculate',
            'label' => 'احتساب الرواتب',
            'variant' => 'primary',
            'title' => 'احتساب رواتب الموظفين المحددين لهذا الشهر',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_cancel_calc',
            'label' => 'إلغاء الاحتساب',
            'variant' => 'secondary',
            'title' => 'إلغاء احتساب الموظفين المحددين (محتسب فقط)',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_post',
            'label' => 'ترحيل الرواتب',
            'variant' => 'primary',
            'title' => 'ترحيل جميع القيود المحتسبة لهذا الشهر',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'payroll_unpost',
            'label' => 'فك الترحيل',
            'variant' => 'secondary',
            'title' => 'فك ترحيل رواتب الشهر (يلغي الاحتساب بالكامل)',
            'screens' => ['hr_payroll_posting'],
            'permission' => 'action_unpost_payroll',
        ],
        [
            'action' => 'select_slip',
            'label' => 'تحديد القسائم',
            'variant' => 'secondary',
            'title' => 'تحديد جميع الموظفين المحتسبين والمرحّلين لطباعة القسائم',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'select_pending',
            'label' => 'إضافة الموظفين',
            'variant' => 'secondary',
            'title' => 'تحديد الموظفين المفتوحين القابلين للاحتساب',
            'screens' => ['hr_payroll_posting'],
        ],
        [
            'action' => 'print_slip',
            'label' => 'قسيمة الراتب',
            'variant' => 'secondary',
            'title' => 'عرض قسيمة راتب لكل موظف محدّد بمربع التحديد (صفحة لكل موظف)',
            'screens' => ['hr_salaries', 'hr_payroll_posting'],
        ],
        [
            'action' => 'print',
            'label' => 'طباعة',
            'variant' => 'secondary',
            'title' => 'طباعة المستند',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'purchase_invoices',
                'purchase_orders',
                'purchase_returns',
                'report_sales',
                'report_sales_between_dates',
                'report_purchases',
                'report_purchases_by_item',
                'report_sales_by_rep',
                'report_sales_by_region',
                'report_sales_by_item',
                'report_customer_orders',
                'report_sales_returns',
                'report_sales_returns_totals',
                'report_purchase_returns',
                'report_sales_qty_extra',
                'report_sales_invoice_discount',
                'report_sales_delivery',
                'report_customers',
                'report_customers_by_rep',
                'report_suppliers',
                'report_hr_employees',
                'report_hr_employees_by_department',
                'report_hr_employees_by_nationality',
                'report_hr_employees_resigned',
                'report_chart_of_accounts',
                'report_party_statement',
                'report_oracle_customer_statement',
                'report_customer_statement',
                'report_supplier_statement',
                'report_receivables',
                'report_receivables_aging',
                'report_incoming_checks',
                'report_outgoing_checks',
                'fin_outgoing_checks',
                'report_supplier_payables',
                'report_vouchers',
                'report_audit_log',
                'item_stock_movements',
                'warehouse_moves',
                'inventory_stocktake',
                'report_warehouse_items',
                'report_customer_purchases_by_item',
                'report_warehouse_zero_qty',
                'report_warehouse_negative_qty',
                'report_warehouse_financial',
                'report_warehouse_moves',
                'report_trial_balance',
                'report_trial_balance_detailed',
                'report_general_ledger',
                'report_account_statement',
                'report_income_statement',
                'report_income_statement_comprehensive',
                'report_tax_declaration',
                'report_tax_ar3',
                'report_vat_net_payable',
                'report_balance_sheet',
                'hr_payroll_month_report',
                'hr_payroll_dept_report',
                'hr_payroll_ss_report',
                'hr_payroll_income_tax_report',
                'hr_payroll_bank_transfer_report',
                'hr_payroll_slip_report',
                'report_hr_employee_advances',
                'report_hr_employee_overtime',
                'report_hr_employee_attendance',
                'report_hr_att_punch_movements',
                'report_hr_employee_leaves',
                'report_hr_employee_leave_balances',
                'report_hr_employee_departures',
                'hr_employees',
                'hr_employee_attendance',
                'hr_attendance_sync_server',
                'hr_attendance_sync_local',
                'hr_attendance_settings',
                'hr_employee_schedule',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_employee_overtime',
                'hr_overtime_settings',
                'hr_payroll_posting',
                'journal_voucher',
                'sales_invoice_gps',
                'user_gps_locations',
                'user_gps_tracker',
            ],
        ],
        [
            'action' => 'excel',
            'label' => 'Excel',
            'variant' => 'secondary',
            'title' => 'تصدير Excel',
            'screens' => [
                'sales_invoices',
                'sales_delivery',
                'cash_receipt',
                'purchase_invoices',
                'report_sales',
                'report_sales_between_dates',
                'report_purchases',
                'report_purchases_by_item',
                'report_sales_by_rep',
                'report_sales_by_region',
                'report_sales_by_item',
                'report_customer_orders',
                'report_sales_returns',
                'report_sales_returns_totals',
                'report_purchase_returns',
                'report_sales_qty_extra',
                'report_sales_invoice_discount',
                'report_sales_delivery',
                'report_customers',
                'report_customers_by_rep',
                'report_suppliers',
                'report_hr_employees',
                'report_hr_employees_by_department',
                'report_hr_employees_by_nationality',
                'report_hr_employees_resigned',
                'report_chart_of_accounts',
                'report_party_statement',
                'report_oracle_customer_statement',
                'report_customer_statement',
                'report_supplier_statement',
                'report_receivables',
                'report_receivables_aging',
                'report_incoming_checks',
                'report_outgoing_checks',
                'report_supplier_payables',
                'report_vouchers',
                'report_audit_log',
                'item_stock_movements',
                'warehouse_moves',
                'inventory_stocktake',
                'report_warehouse_items',
                'report_customer_purchases_by_item',
                'report_warehouse_zero_qty',
                'report_warehouse_negative_qty',
                'report_warehouse_financial',
                'report_warehouse_moves',
                'report_trial_balance',
                'report_trial_balance_detailed',
                'report_general_ledger',
                'report_account_statement',
                'report_income_statement',
                'report_income_statement_comprehensive',
                'report_tax_declaration',
                'report_tax_ar3',
                'report_vat_net_payable',
                'report_balance_sheet',
                'hr_payroll_ss_report',
                'hr_payroll_income_tax_report',
                'hr_payroll_bank_transfer_report',
            ],
        ],
        [
            'action' => 'send_einvoice',
            'label' => 'إرسال للفوترة',
            'variant' => 'secondary',
            'title' => 'إرسال الفاتورة إلى نظام الفوترة الأردني',
            'screens' => ['sales_invoices'],
            'permission' => 'sales_send_einvoice',
        ],
        [
            'action' => 'send_email',
            'label' => 'Send Email',
            'variant' => 'secondary',
            'title' => 'إرسال المستند كـ PDF عبر البريد الإلكتروني',
            'screens' => [
                'sales_invoices',
                'purchase_invoices',
                'sales_returns',
                'purchase_returns',
            ],
        ],
        [
            'action' => 'send_return_einvoice',
            'label' => 'إرجاع للفوترة',
            'variant' => 'secondary',
            'title' => 'إرسال إشعار دائن (إرجاع) للفاتورة في نظام الفوترة الأردني',
            'screens' => ['sales_returns'],
            'permission' => 'sales_send_einvoice',
        ],
        [
            'action' => 'delete',
            'label' => 'حذف',
            'variant' => 'danger',
            'title' => 'مسح أو حذف المستند',
            'screens' => [
                'sales_invoices',
                'sales_invoices_list',
                'sales_delivery',
                'cash_receipt',
                'cash_receipts_list',
                'cash_payment',
                'cash_payments_list',
                'sales_returns',
                'sales_returns_list',
                'purchase_invoices',
                'purchase_invoices_list',
                'purchase_orders',
                'purchase_orders_list',
                'purchase_returns',
                'purchase_returns_list',
                'debit_notes',
                'credit_notes',
                'journal_voucher',
                'warehouse_moves',
                'inventory_stocktake',
                'hr_employees',
                'hr_employee_attendance',
                'hr_attendance_sync_server',
                'hr_attendance_sync_local',
                'hr_attendance_settings',
                'hr_employee_schedule',
                'hr_departments',
                'hr_nationalities',
                'hr_job_titles',
                'hr_payroll_components',
                'hr_salary_banks',
                'hr_employee_bank_link',
                'hr_salaries',
                'hr_employee_advances',
                'hr_monthly_payroll_adjustments',
                'hr_employee_overtime',
                'hr_overtime_settings',
                'hr_social_security_rates',
                'hr_income_tax_settings',
                'sales_customer_orders_approve',
                'sales_customer_order_entry',
                'sales_customer_order_entry_approve',
            ],
            'permission_by_screen' => [
                'sales_customer_orders_approve' => 'action_delete_customer_order',
                'sales_customer_order_entry' => 'action_delete_customer_order',
                'sales_customer_order_entry_approve' => 'action_delete_customer_order',
                'sales_invoices' => 'action_delete_sales_invoice',
                'sales_invoices_list' => 'action_delete_sales_invoice',
                'sales_delivery' => 'action_delete_sales_delivery',
                'cash_receipt' => 'action_delete_cash_receipt',
                'cash_receipts_list' => 'action_delete_cash_receipt',
                'cash_payment' => 'action_delete_cash_payment',
                'cash_payments_list' => 'action_delete_cash_payment',
                'sales_returns' => 'action_delete_sales_return',
                'sales_returns_list' => 'action_delete_sales_return',
                'purchase_invoices' => 'action_delete_purchase_invoice',
                'purchase_invoices_list' => 'action_delete_purchase_invoice',
                'purchase_orders' => 'action_delete_purchase_order',
                'purchase_orders_list' => 'action_delete_purchase_order',
                'purchase_returns' => 'action_delete_purchase_return',
                'purchase_returns_list' => 'action_delete_purchase_return',
                'debit_notes' => 'action_delete_debit_note',
                'credit_notes' => 'action_delete_credit_note',
                'journal_voucher' => 'action_delete_journal_voucher',
                'warehouse_moves' => 'action_delete_warehouse_move',
                'inventory_stocktake' => 'action_delete_inventory_stocktake',
            ],
        ],
        [
            'action' => 'exit',
            'label' => 'خروج',
            'variant' => 'secondary',
            'title' => 'العودة إلى قائمة الأيقونات أو لوحة التحكم',
            'display' => 'icon',
        ],
    ],
];
