-- ZKT Attendance Management — schema for MySQL (converted from sqlserver.sql)
-- Run in MySQL Workbench on the same database as ODBC DSN (namma_erp).

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

USE namma_erp;

CREATE TABLE IF NOT EXISTS CHECKEXACT (
	EXACTID INT NOT NULL AUTO_INCREMENT,
	USERID INT NULL DEFAULT 0,
	CHECKTIME DATETIME NULL DEFAULT NULL,
	CHECKTYPE VARCHAR(2) NULL DEFAULT NULL,
	ISADD SMALLINT NULL DEFAULT 0,
	YUYIN VARCHAR(25) NULL,
	ISMODIFY SMALLINT NULL DEFAULT 0,
	ISDELETE SMALLINT NULL DEFAULT 0,
	INCOUNT SMALLINT NULL DEFAULT 0,
	ISCOUNT SMALLINT NULL DEFAULT 0,
	MODIFYBY VARCHAR(20) NULL,
	`DATE` DATETIME NULL DEFAULT NULL,
	CONSTRAINT EXACTID PRIMARY KEY (EXACTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CHECKINOUT (
	USERID INT NOT NULL,
	CHECKTIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CHECKTYPE VARCHAR(1) NULL DEFAULT 'I',
	VERIFYCODE INT NULL DEFAULT 0,
	SENSORID VARCHAR(5) NULL,
	CONSTRAINT USERCHECKTIME PRIMARY KEY (USERID, CHECKTIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DEPARTMENTS (
	DEPTID INT NOT NULL AUTO_INCREMENT,
	DEPTNAME VARCHAR(30) NULL,
	SUPDEPTID INT NOT NULL DEFAULT 1,
	CONSTRAINT DEPTID PRIMARY KEY (DEPTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS EXCNOTES (
	USERID INT NULL,
	ATTDATE DATETIME NULL DEFAULT NULL,
	NOTES VARCHAR(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS HOLIDAYS (
	HOLIDAYID INT NOT NULL AUTO_INCREMENT,
	HOLIDAYNAME VARCHAR(20) NULL,
	HOLIDAYYEAR SMALLINT NULL,
	HOLIDAYMONTH SMALLINT NULL,
	HOLIDAYDAY SMALLINT NULL DEFAULT 1,
	STARTTIME DATETIME NULL DEFAULT NULL,
	DURATION SMALLINT NULL,
	HOLIDAYTYPE SMALLINT NULL,
	XINBIE VARCHAR(4) NULL,
	MINZU VARCHAR(50) NULL,
	CONSTRAINT HOLID PRIMARY KEY (HOLIDAYID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS NUM_RUN (
	NUM_RUNID INT NOT NULL AUTO_INCREMENT,
	OLDID INT NULL DEFAULT -1,
	NAME VARCHAR(30) NOT NULL,
	STARTDATE DATETIME NULL DEFAULT '1900-01-01 00:00:00',
	ENDDATE DATETIME NULL DEFAULT '2099-12-31 00:00:00',
	CYLE SMALLINT NULL DEFAULT 1,
	UNITS SMALLINT NULL DEFAULT 1,
	CONSTRAINT NUMID PRIMARY KEY (NUM_RUNID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS NUM_RUN_DEIL (
	NUM_RUNID SMALLINT NOT NULL,
	STARTTIME DATETIME NOT NULL,
	ENDTIME DATETIME NULL DEFAULT NULL,
	SDAYS SMALLINT NOT NULL,
	EDAYS SMALLINT NULL,
	SCHCLASSID INT NULL DEFAULT -1,
	CONSTRAINT NUMID2 PRIMARY KEY (NUM_RUNID, SDAYS, STARTTIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SECURITYDETAILS (
	SECURITYDETAILID INT NOT NULL AUTO_INCREMENT,
	USERID SMALLINT NULL,
	DEPTID SMALLINT NULL,
	SCHEDULE SMALLINT NULL,
	USERINFO SMALLINT NULL,
	ENROLLFINGERS SMALLINT NULL,
	REPORTVIEW SMALLINT NULL,
	REPORT VARCHAR(10) NULL,
	CONSTRAINT NAMEID2 PRIMARY KEY (SECURITYDETAILID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SHIFT (
	SHIFTID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NULL,
	USHIFTID INT NULL DEFAULT -1,
	STARTDATE DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00',
	ENDDATE DATETIME NULL DEFAULT '1900-12-31 00:00:00',
	RUNNUM SMALLINT NULL DEFAULT 0,
	SCH1 INT NULL DEFAULT 0,
	SCH2 INT NULL DEFAULT 0,
	SCH3 INT NULL DEFAULT 0,
	SCH4 INT NULL DEFAULT 0,
	SCH5 INT NULL DEFAULT 0,
	SCH6 INT NULL DEFAULT 0,
	SCH7 INT NULL DEFAULT 0,
	SCH8 INT NULL DEFAULT 0,
	SCH9 INT NULL DEFAULT 0,
	SCH10 INT NULL DEFAULT 0,
	SCH11 INT NULL DEFAULT 0,
	SCH12 INT NULL DEFAULT 0,
	CYCLE SMALLINT NULL DEFAULT 0,
	UNITS SMALLINT NULL DEFAULT 0,
	CONSTRAINT SHIFTS PRIMARY KEY (SHIFTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TEMPLATE (
	TEMPLATEID INT NOT NULL AUTO_INCREMENT,
	USERID INT NOT NULL,
	FINGERID INT NOT NULL,
	TEMPLATE LONGBLOB NOT NULL,
	TEMPLATE2 LONGBLOB NULL,
	TEMPLATE3 LONGBLOB NULL,
	BITMAPPICTURE LONGBLOB NULL,
	BITMAPPICTURE2 LONGBLOB NULL,
	BITMAPPICTURE3 LONGBLOB NULL,
	BITMAPPICTURE4 LONGBLOB NULL,
	USETYPE SMALLINT NULL,
	CONSTRAINT TEMPLATED PRIMARY KEY (TEMPLATEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_OF_RUN (
	USERID INT NOT NULL,
	NUM_OF_RUN_ID INT NOT NULL,
	STARTDATE DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00',
	ENDDATE DATETIME NOT NULL DEFAULT '2099-12-31 00:00:00',
	ISNOTOF_RUN INT NULL DEFAULT 0,
	ORDER_RUN INT NULL,
	CONSTRAINT USER_ST_NUM PRIMARY KEY (USERID, NUM_OF_RUN_ID, STARTDATE, ENDDATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_SPEDAY (
	USERID INT NOT NULL,
	STARTSPECDAY DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00',
	ENDSPECDAY DATETIME NULL DEFAULT '2099-12-31 00:00:00',
	DATEID SMALLINT NOT NULL DEFAULT -1,
	YUANYING VARCHAR(200) NULL,
	`DATE` DATETIME NULL DEFAULT NULL,
	CONSTRAINT USER_SEP PRIMARY KEY (USERID, STARTSPECDAY, DATEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_TEMP_SCH (
	USERID INT NOT NULL,
	COMETIME DATETIME NOT NULL,
	LEAVETIME DATETIME NOT NULL,
	OVERTIME INT NOT NULL DEFAULT 0,
	`TYPE` SMALLINT NULL DEFAULT 0,
	FLAG SMALLINT NULL DEFAULT 1,
	SCHCLASSID INT NULL DEFAULT -1,
	CONSTRAINT USER_TEMP PRIMARY KEY (USERID, COMETIME, LEAVETIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USERINFO (
	USERID INT NOT NULL AUTO_INCREMENT,
	BADGENUMBER VARCHAR(12) NOT NULL,
	SSN VARCHAR(20) NULL,
	NAME VARCHAR(20) NULL,
	GENDER VARCHAR(2) NULL,
	TITLE VARCHAR(20) NULL,
	PAGER VARCHAR(20) NULL,
	BIRTHDAY DATETIME NULL DEFAULT NULL,
	HIREDDAY DATETIME NULL DEFAULT NULL,
	STREET VARCHAR(40) NULL,
	CITY VARCHAR(2) NULL,
	STATE VARCHAR(2) NULL,
	ZIP VARCHAR(12) NULL,
	OPHONE VARCHAR(20) NULL,
	FPHONE VARCHAR(20) NULL,
	VERIFICATIONMETHOD SMALLINT NULL,
	DEFAULTDEPTID SMALLINT NULL DEFAULT 1,
	SECURITYFLAGS SMALLINT NULL,
	ATT SMALLINT NOT NULL DEFAULT 1,
	INLATE SMALLINT NOT NULL DEFAULT 1,
	OUTEARLY SMALLINT NOT NULL DEFAULT 1,
	OVERTIME SMALLINT NOT NULL DEFAULT 1,
	SEP SMALLINT NOT NULL DEFAULT 1,
	HOLIDAY SMALLINT NOT NULL DEFAULT 1,
	MINZU VARCHAR(8) NULL,
	`PASSWORD` VARCHAR(20) NULL,
	LUNCHDURATION SMALLINT NOT NULL DEFAULT 1,
	MVerifyPass VARCHAR(10) NULL,
	PHOTO LONGBLOB NULL,
	CONSTRAINT USERIDS PRIMARY KEY (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX USERFINGER ON TEMPLATE (USERID, FINGERID);
CREATE UNIQUE INDEX HOLIDAYNAME ON HOLIDAYS (HOLIDAYNAME);
CREATE INDEX DEPTNAME ON DEPARTMENTS (DEPTNAME);
CREATE UNIQUE INDEX EXCNOTE ON EXCNOTES (USERID, ATTDATE);
CREATE UNIQUE INDEX BADGENUMBER ON USERINFO (BADGENUMBER);

CREATE TABLE IF NOT EXISTS LeaveClass (
	LeaveId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LeaveName VARCHAR(20) NOT NULL,
	MinUnit DOUBLE NOT NULL DEFAULT 1,
	Unit SMALLINT NOT NULL DEFAULT 1,
	RemaindProc SMALLINT NOT NULL DEFAULT 1,
	RemaindCount SMALLINT NOT NULL DEFAULT 1,
	ReportSymbol VARCHAR(4) NOT NULL DEFAULT '-',
	Deduct DOUBLE NOT NULL DEFAULT 0,
	Color INT NOT NULL DEFAULT 0,
	Classify SMALLINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS LeaveClass1 (
	LeaveId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LeaveName VARCHAR(20) NOT NULL,
	MinUnit DOUBLE NOT NULL DEFAULT 1,
	Unit SMALLINT NOT NULL DEFAULT 0,
	RemaindProc SMALLINT NOT NULL DEFAULT 2,
	RemaindCount SMALLINT NOT NULL DEFAULT 1,
	ReportSymbol VARCHAR(4) NOT NULL DEFAULT '-',
	Deduct DOUBLE NOT NULL DEFAULT 0,
	LeaveType SMALLINT NOT NULL DEFAULT 0,
	Color INT NOT NULL DEFAULT 0,
	Classify SMALLINT NOT NULL DEFAULT 0,
	Calc TEXT NULL
) ENGINE=InnoDB AUTO_INCREMENT=999 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SchClass (
	schClassid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	schName VARCHAR(20) NOT NULL,
	StartTime DATETIME NOT NULL,
	EndTime DATETIME NOT NULL,
	LateMinutes INT NULL,
	EarlyMinutes INT NULL,
	CheckIn INT NULL DEFAULT 1,
	CheckOut INT NULL DEFAULT 1,
	CheckInTime1 DATETIME NULL DEFAULT NULL,
	CheckInTime2 DATETIME NULL DEFAULT NULL,
	CheckOutTime1 DATETIME NULL DEFAULT NULL,
	CheckOutTime2 DATETIME NULL DEFAULT NULL,
	Color INT NULL DEFAULT 16715535,
	AutoBind SMALLINT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- غير موجود في sqlserver.sql — البرنامج يحتاجه عند ربط الجهاز
CREATE TABLE IF NOT EXISTS Machines (
	ID INT NOT NULL AUTO_INCREMENT,
	MachineAlias VARCHAR(20) NULL,
	ConnectType INT NULL DEFAULT 1,
	IP VARCHAR(20) NULL,
	SerialPort INT NULL DEFAULT 1,
	Port INT NULL DEFAULT 4370,
	Baudrate INT NULL DEFAULT 115200,
	MachineNumber INT NULL DEFAULT 1,
	IsHost SMALLINT NULL DEFAULT 0,
	Enabled SMALLINT NULL DEFAULT 1,
	CommPassword VARCHAR(12) NULL,
	UILanguage SMALLINT NULL DEFAULT 0,
	DateFormat INT NULL DEFAULT 0,
	InPort INT NULL DEFAULT 0,
	OutPort INT NULL DEFAULT 0,
	FirmwareVersion VARCHAR(30) NULL,
	ProductType VARCHAR(20) NULL,
	LockControl INT NULL DEFAULT 0,
	Purpose INT NULL DEFAULT 0,
	ProduceKind INT NULL DEFAULT 0,
	sn VARCHAR(20) NULL,
	PhotoStamp VARCHAR(20) NULL DEFAULT '0',
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS AttParam (
	PARANAME VARCHAR(20) NOT NULL PRIMARY KEY,
	PARATYPE VARCHAR(2) NULL,
	PARAVALUE VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO DEPARTMENTS (DEPTNAME, SUPDEPTID) VALUES ('Our Company', 0);

INSERT INTO LeaveClass (LeaveName, Unit, ReportSymbol, Color)
VALUES ('Sick', 1, 'B', 3398744);
INSERT INTO LeaveClass (LeaveName, Unit, ReportSymbol, Color)
VALUES ('Vacation', 1, 'S', 8421631);
INSERT INTO LeaveClass (LeaveName, Unit, ReportSymbol, Color)
VALUES ('Other', 1, 'T', 16744576);

INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('BLeave', 0.5, 3, 1, 1, 'G', 3, 'if(AttItem(LeaveType1)=999,AttItem(LeaveTime1),0)+if(AttItem(LeaveType2)=999,AttItem(LeaveTime2),0)+if(AttItem(LeaveType3)=999,AttItem(LeaveTime3),0)+if(AttItem(LeaveType4)=999,AttItem(LeaveTime4),0)+if(AttItem(LeaveType5)=999,AttItem(LeaveTime5),0)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('Normal', 0.5, 3, 1, 0, ' ', 3);
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('Late', 10, 2, 2, 1, '>', 3, 'AttItem(minLater)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('Early', 10, 2, 2, 1, '<', 3, 'AttItem(minEarly)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('AfL', 1, 1, 1, 1, 'L', 3, 'if((AttItem(LeaveType1)>0) and (AttItem(LeaveType1)<999),AttItem(LeaveTime1),0)+if((AttItem(LeaveType2)>0) and (AttItem(LeaveType2)<999),AttItem(LeaveTime2),0)+if((AttItem(LeaveType3)>0) and (AttItem(LeaveType3)<999),AttItem(LeaveTime3),0)+if((AttItem(LeaveType4)>0) and (AttItem(LeaveType4)<999),AttItem(LeaveTime4),0)+if((AttItem(LeaveType5)>0) and (AttItem(LeaveType5)<999),AttItem(LeaveTime5),0)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('Absent', 0.5, 3, 1, 0, 'A', 3, 'AttItem(MinAbsent)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('OT', 1, 1, 1, 1, '+', 3, 'AttItem(MinOverTime)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('OT2', 1, 1, 0, 1, '=', 0, 'if(HolidayId(1)=1, AttItem(MinOverTime),0)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('Rest', 0.5, 3, 2, 1, '-', 2);
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('N/In', 1, 4, 2, 1, '[', 2, 'If(AttItem(CheckIn)=null,If(AttItem(OnDuty)=null,0,if(((AttItem(LeaveStart1)=null) or (AttItem(LeaveStart1)>AttItem(OnDuty))) and AttItem(DutyOn),1,0)),0)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType, Calc)
VALUES ('N/Out', 1, 4, 2, 1, ']', 2, 'If(AttItem(CheckOut)=null,If(AttItem(OffDuty)=null,0,if((AttItem(LeaveEnd1)=null) or (AttItem(LeaveEnd1)<AttItem(OffDuty)),if((AttItem(LeaveEnd2)=null) or (AttItem(LeaveEnd2)<AttItem(OffDuty)),if(((AttItem(LeaveEnd3)=null) or (AttItem(LeaveEnd3)<AttItem(OffDuty))) and AttItem(DutyOff),1,0),0),0)),0)');
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('ROT', 1, 4, 2, 1, '{', 3);
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('BOUT', 1, 4, 2, 1, '}', 3);
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('OUT', 1, 1, 2, 1, 'L', 3);
INSERT INTO LeaveClass1 (LeaveName, MinUnit, Unit, RemaindProc, RemaindCount, ReportSymbol, LeaveType)
VALUES ('FOT', 1, 1, 2, 1, 'F', 3);

INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsEarly', '5');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsLate', '10');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsNoBreakIn', '60');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsNoBreakOut', '60');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsNoIn', '60');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsNoLeave', '60');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsNotOverTime', '60');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('MinsWorkDay', '420');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('NoBreakIn', '1012');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('NoBreakOut', '1012');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('NoIn', '1001');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('NoLeave', '1002');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('OutOverTime', '0');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('TwoDay', '0');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('CheckInColor', '16777151');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('CheckOutColor', '12910591');
INSERT INTO AttParam (PARANAME, PARAVALUE) VALUES ('DBVersion', '167');

SET FOREIGN_KEY_CHECKS = 1;
