<?php
declare(strict_types=1);

/**
 * يولّد lang/en.php من قائمة ترجمات مدمجة + مفاتيح القوائم.
 * التشغيل: php tools/build_lang_en.php
 */

$root = dirname(__DIR__);

$extra = [
    // دخول وإعدادات عامة
    'تسجيل الدخول' => 'Login',
    'دخول' => 'Sign in',
    'اسم المستخدم' => 'Username',
    'كلمة المرور' => 'Password',
    'نسيت كلمة المرور؟' => 'Forgot your password?',
    'مرحباً بعودتك' => 'Welcome back',
    'أدخل بياناتك للوصول إلى النظام' => 'Enter your credentials to access the system',
    'عن النظام' => 'About the system',
    'منصة أعمال متكاملة لإدارة العمليات والمالية والمخزون والموارد البشرية من شاشة واحدة.' =>
        'An integrated business platform for operations, finance, inventory, and HR in one place.',
    'لوحة تحكم لحظية' => 'Real-time dashboard',
    'محاسبة ومبيعات ومشتريات' => 'Accounting, sales, and purchases',
    'صلاحيات متعددة وآمنة' => 'Secure multi-user permissions',
    'أدخل اسم المستخدم وكلمة المرور.' => 'Enter username and password.',
    'بيانات الدخول غير صحيحة.' => 'Invalid login credentials.',
    'يرجى تأكيد أنك لست روبوتاً (reCAPTCHA).' => 'Please confirm you are not a robot (reCAPTCHA).',
    'تعذر تسجيل الدخول حالياً. يرجى التحقق من إعدادات قاعدة البيانات ثم المحاولة مرة أخرى.' =>
        'Unable to sign in right now. Check database settings and try again.',
    'لغة النظام' => 'System language',
    'العربية' => 'Arabic',
    'الإنجليزية' => 'English',
    'يمكن تغييرها في أي وقت — تُطبَّق على الواجهة والتقارير والطباعة بعد الحفظ.' =>
        'Can be changed anytime — applies to UI, reports, and printing after save.',
    'واجهة النظام' => 'System interface',
    'الواجهة الحالية' => 'Current interface',
    'الواجهة الحديثة' => 'Modern interface',
    'يمكن تغييرها في أي وقت — تُطبَّق على شاشة الدخول ولوحة النظام بعد الحفظ.' =>
        'Can be changed anytime — applies to login and the app after save.',
    'بيانات الشركة' => 'Company details',
    'اسم الشركة' => 'Company name',
    'العنوان' => 'Address',
    'الهاتف' => 'Phone',
    'البريد الإلكتروني' => 'Email',
    'العملة' => 'Currency',
    'حفظ الإعدادات' => 'Save settings',
    'تم حفظ الإعدادات بنجاح.' => 'Settings saved successfully.',
    'انتهت صلاحية الجلسة، أعد المحاولة.' => 'Session expired, please try again.',
    'تسجيل خروج' => 'Sign out',
    'مدير النظام' => 'System Admin',
    'مرحباً، :name' => 'Welcome, :name',
    'ملخص الأداء المالي والتشغيلي' => 'Financial and operational performance summary',
    'القائمة' => 'Menu',
    'المفضلة' => 'Favorites',
    'إحداثيات مواقع فواتير البيع' => 'Sales invoice GPS locations',
    'شريط الإجراءات' => 'Action toolbar',
    'الخروج والعودة إلى قائمة الشاشات' => 'Exit and return to the screen list',
    'الخروج والعودة إلى لوحة التحكم' => 'Exit and return to the dashboard',
    'العودة إلى ' => 'Back to ',
    'النظام المحاسبي' => 'Accounting System',
    'الشركة' => 'Company',

    // طباعة ومستندات شائعة
    'فاتورة مبيعات' => 'Sales invoice',
    'فاتورة شراء' => 'Purchase invoice',
    'سند قبض' => 'Receipt voucher',
    'سند صرف' => 'Payment voucher',
    'سند قيد' => 'Journal voucher',
    'مرتجع مبيعات' => 'Sales return',
    'مردود مشتريات' => 'Purchase return',
    'سند تسليم بضاعة' => 'Goods delivery note',
    'حركة مستودع' => 'Warehouse movement',
    'كشف حساب' => 'Account statement',
    'قسيمة راتب' => 'Payslip',
    'قسيمة الراتب' => 'Payslip',
    'طباعة موظف' => 'Employee print',
    'من' => 'From',
    'إلى' => 'To',
    'التاريخ' => 'Date',
    'الوقت' => 'Time',
    'الرقم' => 'Number',
    'البيان' => 'Description',
    'المبلغ' => 'Amount',
    'الإجمالي' => 'Total',
    'الخصم' => 'Discount',
    'الضريبة' => 'Tax',
    'الصافي' => 'Net',
    'الكمية' => 'Quantity',
    'السعر' => 'Price',
    'المادة' => 'Item',
    'الوحدة' => 'Unit',
    'العميل' => 'Customer',
    'المورد' => 'Supplier',
    'المندوب' => 'Sales rep',
    'المستودع' => 'Warehouse',
    'الحساب' => 'Account',
    'مدين' => 'Debit',
    'دائن' => 'Credit',
    'الرصيد' => 'Balance',
    'ملاحظات' => 'Notes',
    'حالة' => 'Status',
    'مسودة' => 'Draft',
    'مرحّل' => 'Posted',
    'ملغى' => 'Cancelled',
    'بحث' => 'Search',
    'تصفية' => 'Filter',
    'عرض' => 'View',
    'تصدير' => 'Export',
    'طباعة' => 'Print',
    'إغلاق' => 'Close',
    'موافق' => 'OK',
    'إلغاء' => 'Cancel',
    'نعم' => 'Yes',
    'لا' => 'No',
    'تحميل...' => 'Loading...',
    'لا توجد بيانات' => 'No data',
    'الصفحة' => 'Page',
    'من أصل' => 'of',
    'السابق' => 'Previous',
    'التالي' => 'Next',
    'رقم الصفحة' => 'Page number',
    'تقرير' => 'Report',
    'الفترة' => 'Period',
    'اليوم' => 'Today',
    'هذا الشهر' => 'This month',
    'إجمالي المبيعات' => 'Total sales',
    'مبيعات هذا الشهر' => 'Sales this month',
    'صافي المبيعات' => 'Net sales',
    'إجمالي المشتريات' => 'Total purchases',
    'قيود اليومية' => 'Journal entries',
    'مستخدم النظام' => 'System user',
    'توقيع المستلم' => 'Recipient signature',
    'تحديث الصفحة' => 'Refresh page',
    'الشاشة الرئيسية' => 'Home screen',
    'تم حفظ الإعدادات.' => 'Settings saved.',
];

// ترجمات القوائم وشريط الأدوات
$menu = [
    'Excel' => 'Excel',
    'Send Email' => 'Send Email',
    'آخر فواتير المبيعات' => 'Recent sales invoices',
    'أرشيف' => 'Archive',
    'أرصدة الإجازات لجميع الموظفين' => 'Leave balances for all employees',
    'أرصدة المستودع المالية' => 'Warehouse financial balances',
    'أعمار الذمم' => 'Receivables aging',
    'أمانات ضريبة مبيعات' => 'VAT net payable',
    'أنواع المغادرات' => 'Departure types',
    'إجمالي المرتجعات' => 'Returns totals',
    'إدخال الإجازات' => 'Enter leaves',
    'إرجاع عهدة' => 'Return custody',
    'إرجاع للفوترة' => 'Return e-invoice',
    'إرسال إشعار دائن (إرجاع) للفاتورة في نظام الفوترة الأردني' => 'Send credit note (return) to Jordan e-invoicing',
    'إرسال الفاتورة إلى نظام الفوترة الأردني' => 'Send invoice to Jordan e-invoicing',
    'إرسال المستند كـ PDF عبر البريد الإلكتروني' => 'Email document as PDF',
    'إرسال للفوترة' => 'Send to e-invoicing',
    'إشعارات دائنة' => 'Credit notes',
    'إشعارات مدينة' => 'Debit notes',
    'إضافة الموظفين' => 'Add employees',
    'إضافة عميل' => 'Add customer',
    'إعداد أنواع الحركات' => 'Movement types setup',
    'إعداد العلاوات والاقتطاعات' => 'Allowances & deductions setup',
    'إعدادات الإجازات' => 'Leave settings',
    'إعدادات الرواتب' => 'Payroll settings',
    'إعدادات العمل الإضافي' => 'Overtime settings',
    'إعدادات الفوترة' => 'E-invoicing settings',
    'إعدادات النظام' => 'System settings',
    'إعدادات تتبّع الهاتف' => 'Phone tracking settings',
    'إعدادات دوام الموظفين' => 'Attendance settings',
    'إعدادات ضريبة الدخل' => 'Income tax settings',
    'إغلاق الأشهر المحاسبية' => 'Close accounting periods',
    'إقفال السنة المالية' => 'Year-end closing',
    'إلغاء احتساب الموظفين المحددين (محتسب فقط)' => 'Cancel calculation for selected employees (calculated only)',
    'إلغاء الاحتساب' => 'Cancel calculation',
    'إلغاء السند' => 'Cancel voucher',
    'إلغاء السند المرحّل (يبقى برقم التسلسل ويُلغى أثره المحاسبي)' => 'Cancel posted voucher (keeps number, reverses GL impact)',
    'احتساب الرواتب' => 'Calculate payroll',
    'احتساب رواتب الموظفين المحددين لهذا الشهر' => 'Calculate selected employees for this month',
    'اعتماد طلبات الشراء' => 'Approve purchase orders',
    'الأرباح والخسائر' => 'Profit & loss',
    'الأرصدة الافتتاحية' => 'Opening balances',
    'الأقسام' => 'Departments',
    'الإجازات' => 'Leaves',
    'الإعدادات' => 'Settings',
    'الإقرار الضريبي' => 'Tax declaration',
    'البنوك' => 'Banks',
    'الجرد' => 'Stocktaking',
    'الجلسات المفتوحة' => 'Open sessions',
    'الجنسيات' => 'Nationalities',
    'الخصم على الفواتير' => 'Invoice discounts',
    'الرئيسية' => 'Home',
    'الرواتب' => 'Payroll',
    'السلف' => 'Advances',
    'الشيكات الواردة' => 'Incoming checks',
    'الصلاحيات' => 'Permissions',
    'العمل الإضافي' => 'Overtime',
    'العملاء' => 'Customers',
    'العمليات المالية' => 'Financial operations',
    'العودة إلى قائمة الأيقونات أو لوحة التحكم' => 'Back to icon list or dashboard',
    'القيود المحاسبية' => 'Journal entries',
    'المبيعات' => 'Sales',
    'المجموعات' => 'Groups',
    'المحاسبة' => 'Accounting',
    'المستخدمون' => 'Users',
    'المستخدمون والصلاحيات' => 'Users & permissions',
    'المستودعات' => 'Warehouses',
    'المسميات الوظيفية' => 'Job titles',
    'المشتريات' => 'Purchases',
    'المغادرات' => 'Departures',
    'المندوبين' => 'Sales reps',
    'المواد التي رصيدها صفر' => 'Items with zero stock',
    'المواد والأصناف' => 'Items',
    'الموردين' => 'Suppliers',
    'الموظفين المستقيلين' => 'Resigned employees',
    'الموظفين حسب الجنسية' => 'Employees by nationality',
    'الموظفين حسب القسم' => 'Employees by department',
    'الميزانية العمومية' => 'Balance sheet',
    'النسخ الاحتياطي' => 'Backup',
    'النظام' => 'System',
    'بحث' => 'Search',
    'بحث بالرقم في المستند الحالي أو في قائمة الترحيل' => 'Search by number in current document or posting list',
    'بصمات الموظفين' => 'Employee attendance',
    'بيانات الموظف الاساسية' => 'Employee master data',
    'تتبّع المواقع الحية' => 'Live location tracking',
    'تحديد القسائم' => 'Select payslips',
    'تحديد الموظفين المفتوحين القابلين للاحتساب' => 'Select open employees eligible for calculation',
    'تحديد جميع الموظفين المحتسبين والمرحّلين لطباعة القسائم' => 'Select all calculated/posted employees for payslip print',
    'تحميل عهدة' => 'Load custody',
    'ترحيل' => 'Post',
    'ترحيل الرواتب' => 'Post payroll',
    'ترحيل المستند (بيع: صرف + عميل — مرتجع بيع: عميل — شراء: إدخال + ذمة مورد — مردود شراء: مخزون + ذمة)' =>
        'Post document (sales/purchase stock & AR/AP impact)',
    'ترحيل جميع القيود المحتسبة لهذا الشهر' => 'Post all calculated entries for this month',
    'ترحيل سندات الصرف' => 'Post payment vouchers',
    'ترحيل سندات القبض' => 'Post receipt vouchers',
    'ترحيل فواتير الشراء' => 'Post purchase invoices',
    'ترحيل فواتير المبيعات' => 'Post sales invoices',
    'ترحيل مرتجعات المبيعات' => 'Post sales returns',
    'ترحيل مردودات المشتريات' => 'Post purchase returns',
    'تسجيل ساعات العمل الإضافي' => 'Record overtime hours',
    'تصدير Excel' => 'Export Excel',
    'تطبيق الهاتف' => 'Mobile app',
    'تعديل' => 'Edit',
    'تعديل أسعار المواد' => 'Adjust item prices',
    'تعديل الأسعار' => 'Price adjustment',
    'تعديل سند مرحّل بعد التحقق بكلمة المرور (فك الترحيل ثم التعديل وإعادة الترحيل)' =>
        'Edit posted voucher after password (unpost, edit, repost)',
    'تعريف دوام الموظف' => 'Employee schedule',
    'تقارير الإجازات' => 'Leave reports',
    'تقارير البصمات' => 'Attendance reports',
    'تقارير الرواتب' => 'Payroll reports',
    'تقارير الضريبة' => 'Tax reports',
    'تقارير العمل الإضافي' => 'Overtime reports',
    'تقارير العملاء' => 'Customer reports',
    'تقارير المبيعات' => 'Sales reports',
    'تقارير المحاسبة' => 'Accounting reports',
    'تقارير المستودعات' => 'Warehouse reports',
    'تقارير المشتريات' => 'Purchase reports',
    'تقارير المغادرات' => 'Departure reports',
    'تقارير المندوبين' => 'Sales rep reports',
    'تقارير الموردين' => 'Supplier reports',
    'تقارير الموظفين' => 'Employee reports',
    'تقارير سند التسليم' => 'Delivery note reports',
    'تقارير طلبات الشراء' => 'Purchase order reports',
    'تقارير مرتجعات المبيعات' => 'Sales return reports',
    'تقرير الإجازات بين تاريخين' => 'Leaves between dates',
    'تقرير الشيكات الصادرة' => 'Outgoing checks report',
    'تقرير الشيكات الواردة' => 'Incoming checks report',
    'تقرير الضريبة (أر/3)' => 'Tax report (AR/3)',
    'تقرير الطلبات المفتوحة' => 'Open orders report',
    'تقرير العمل الإضافي' => 'Overtime report',
    'تقرير العملاء' => 'Customers report',
    'تقرير القيود' => 'Journal report',
    'تقرير الكميات الإضافية على الفواتير' => 'Extra quantities on invoices',
    'تقرير المبيعات الشهري حسب العميل' => 'Monthly sales by customer',
    'تقرير المبيعات بين تاريخين' => 'Sales between dates',
    'تقرير المبيعات حسب المادة' => 'Sales by item',
    'تقرير المبيعات حسب المندوب' => 'Sales by rep',
    'تقرير المرتجعات' => 'Returns report',
    'تقرير المشتريات بين تاريخين' => 'Purchases between dates',
    'تقرير المشتريات حسب المادة' => 'Purchases by item',
    'تقرير المغادرات بين تاريخين' => 'Departures between dates',
    'تقرير المواد' => 'Items report',
    'تقرير المواد السالبة' => 'Negative stock report',
    'تقرير الموردين' => 'Suppliers report',
    'تقرير الموظفين' => 'Employees report',
    'تقرير حركات المستودعات' => 'Warehouse movements report',
    'تقرير سلف الموظفين' => 'Employee advances report',
    'تقرير سندات البضاعة' => 'Delivery notes report',
    'تقرير سندات القبض / الصرف' => 'Receipts / payments report',
    'تقرير طلبات الشراء' => 'Purchase orders report',
    'تقرير طلبات الشراء حسب المادة' => 'Purchase orders by item',
    'تقرير قيود الرواتب حسب الشهر' => 'Payroll posting by month',
    'تقرير مرتجعات المشتريات' => 'Purchase returns report',
    'جديد' => 'New',
    'حذف' => 'Delete',
    'حركات البصمات (الكل)' => 'Punch movements (all)',
    'حركات التعديل' => 'Audit log',
    'حركات المستودع' => 'Warehouse movements',
    'حركة دوام الموظفين' => 'Attendance activity',
    'حسابات الشاشة الرئيسية' => 'Dashboard accounts',
    'حفظ' => 'Save',
    'حفظ المستند الحالي (F10)' => 'Save current document (F10)',
    'خروج' => 'Exit',
    'دفتر الأستاذ العام' => 'General ledger',
    'رئيسي' => 'Main',
    'ربط إعدادات البنك' => 'Bank link setup',
    'ربط الحسابات' => 'Account mapping',
    'رصيد إجازات الموظفين' => 'Employee leave balance',
    'رصيد المستودع' => 'Warehouse stock',
    'رواتب الموظفين' => 'Employee salaries',
    'سجل الشيكات الصادرة' => 'Outgoing checks register',
    'سجل جديد' => 'New record',
    'سلف الموظفين' => 'Employee advances',
    'سند التسليم' => 'Delivery note',
    'سند تسليم بضاعة' => 'Goods delivery note',
    'سند جرد المواد' => 'Stocktake voucher',
    'سند صرف' => 'Payment voucher',
    'سند قبض' => 'Receipt voucher',
    'سند قيد' => 'Journal voucher',
    'شؤون الموظفين' => 'HR',
    'شاشات الإجازات' => 'Leave screens',
    'شاشات البصمات' => 'Attendance screens',
    'شاشات الرواتب' => 'Payroll screens',
    'شاشات العمل الإضافي' => 'Overtime screens',
    'شاشات المغادرات' => 'Departure screens',
    'شاشات الموظفين' => 'Employee screens',
    'شاشات الهاتف' => 'Mobile screens',
    'شجرة الحسابات' => 'Chart of accounts',
    'شيكات خاصة' => 'Private checks',
    'ضريبة فواتير البيع' => 'Sales invoice tax',
    'ضريبة فواتير الشراء' => 'Purchase invoice tax',
    'ضريبة مردود البيع' => 'Sales return tax',
    'ضريبة مردود الشراء' => 'Purchase return tax',
    'طباعة' => 'Print',
    'طباعة المستند' => 'Print document',
    'طباعة شجرة الحسابات' => 'Print chart of accounts',
    'طلب شراء' => 'Purchase order',
    'طلبات الشراء' => 'Purchase orders',
    'عام' => 'General',
    'عرض قسيمة راتب لكل موظف محدّد بمربع التحديد (صفحة لكل موظف)' =>
        'Show payslip for each selected employee (one page each)',
    'علاوات واقتطاعات شهرية' => 'Monthly allowances & deductions',
    'فئات المواد' => 'Item categories',
    'فاتورة شراء' => 'Purchase invoice',
    'فاتورة مبيعات' => 'Sales invoice',
    'فك الترحيل' => 'Unpost',
    'فك ترحيل السند (يلغي الأثر على القيود المحاسبية وأرصدة المستودعات ويعيده مسودة)' =>
        'Unpost voucher (reverses GL/stock and sets draft)',
    'فك ترحيل رواتب الشهر (يلغي الاحتساب بالكامل)' => 'Unpost month payroll (clears calculation)',
    'فواتير البيع غير المسددة' => 'Unpaid sales invoices',
    'فواتير الشراء غير المدفوعة' => 'Unpaid purchase invoices',
    'فواتير المبيعات' => 'Sales invoices',
    'قائمة الدخل' => 'Income statement',
    'قائمة السندات الملغاة' => 'Cancelled vouchers list',
    'قائمة المرتجعات' => 'Returns list',
    'قائمة طلبات الشراء' => 'Purchase orders list',
    'قائمة عهدة المندوب' => 'Rep custody list',
    'قائمة فواتير الشراء' => 'Purchase invoices list',
    'قائمة فواتير المبيعات' => 'Sales invoices list',
    'قائمة مردودات المشتريات' => 'Purchase returns list',
    'قسيمة الراتب' => 'Payslip',
    'قوائم الجرد' => 'Stocktake lists',
    'قيد الرواتب' => 'Payroll posting',
    'قيود الضمان' => 'Social security entries',
    'كشف الرواتب للأقسام' => 'Payroll by department',
    'كشف الضمان الاجتماعي' => 'Social security statement',
    'كشف تحويل الرواتب للبنوك' => 'Bank transfer payroll statement',
    'كشف حركات مادة' => 'Item movement statement',
    'كشف حساب' => 'Account statement',
    'كشف حساب مورد - عميل' => 'Supplier / customer statement',
    'كشف ذمم العملاء' => 'Customer receivables',
    'كشف ذمم الموردين' => 'Supplier payables',
    'كشف ضريبة الدخل' => 'Income tax statement',
    'لوحة التحكم' => 'Dashboard',
    'لوحة الصندوق والحسابات' => 'Cash & accounts panel',
    'لوحة المستحقات' => 'Liabilities panel',
    'مؤشر القيود اليومية (مدخلة / مرحّلة)' => 'Daily journals KPI (entered / posted)',
    'مؤشر المشتريات' => 'Purchases KPI',
    'مؤشرات الشاشة الرئيسية' => 'Dashboard KPIs',
    'مؤشرات الشيكات الواردة والصادرة' => 'Incoming & outgoing checks KPIs',
    'مؤشرات المبيعات (إجمالي + الشهر + صافي)' => 'Sales KPIs (total + month + net)',
    'مؤشرات المقبوضات' => 'Receipts KPIs',
    'مؤشرات رئيسية' => 'Key indicators',
    'مرتجع مبيعات' => 'Sales return',
    'مرتجعات المبيعات' => 'Sales returns',
    'مردود مشتريات' => 'Purchase return',
    'مرفقات المستند — رفع قبل الترحيل، أو عرض فقط بعد الترحيل' =>
        'Attachments — upload before posting, view-only after',
    'مزامنة Windows (محلي)' => 'Windows sync (local)',
    'مزامنة السيرفر (ZKT)' => 'Server sync (ZKT)',
    'مسح أو حذف المستند' => 'Clear or delete document',
    'معدّلات الضريبة' => 'Tax rates',
    'مغادرات الموظفين' => 'Employee departures',
    'مواقع المستخدمين' => 'User locations',
    'مواقع فواتير البيع' => 'Sales invoice locations',
    'ميزان المراجعة' => 'Trial balance',
    'ميزان مراجعة تفصيلي' => 'Detailed trial balance',
    'نسب الضمان الاجتماعي' => 'Social security rates',
    'وحدات القياس' => 'Units of measure',
];

$map = array_merge($extra, $menu);

// استخراج أي مفتاح ناقص من القوائم
$nav = require $root . '/config/nav_menu.php';
$tb = require $root . '/config/master_toolbar.php';
$missing = [];
$walk = static function ($n) use (&$walk, &$map, &$missing): void {
    if (!is_array($n)) {
        return;
    }
    foreach ($n as $k => $v) {
        if (($k === 'title' || $k === 'label') && is_string($v) && $v !== '' && !isset($map[$v])) {
            $missing[$v] = $v;
        }
        if (is_array($v)) {
            $walk($v);
        }
    }
};
$walk($nav);
$walk($tb);

if ($missing !== []) {
    fwrite(STDERR, 'Missing translations: ' . count($missing) . "\n");
    foreach (array_keys($missing) as $m) {
        fwrite(STDERR, $m . "\n");
    }
}

ksort($map, SORT_STRING);

$out = "<?php\ndeclare(strict_types=1);\n\n/** ترجمات الإنجليزية — المفتاح هو النص العربي الأصلي */\nreturn [\n";
foreach ($map as $ar => $en) {
    $out .= '    ' . var_export($ar, true) . ' => ' . var_export($en, true) . ",\n";
}
$out .= "];\n";

$dir = $root . '/lang';
if (!is_dir($dir)) {
    mkdir($dir, 0775, true);
}
file_put_contents($dir . '/en.php', $out);
file_put_contents($dir . '/ar.php', "<?php\ndeclare(strict_types=1);\n\n/** العربية هي المصدر — لا حاجة لكتالوج */\nreturn [];\n");
echo 'Wrote ' . count($map) . " EN strings\n";
