-- ============================================================
-- Toad: البحث عن جداول الفئات (CAT / CATEGORY / GROUP)
-- نفّذ كل قسم على حدة (SYSTEM@TAQWA أو مستخدم التطبيق)
-- ============================================================

-- 1) كل الجداول/الأعمدة التي اسمها يشبه فئة
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER IN ('MAS', 'ACCINV')
  AND (
       UPPER(COLUMN_NAME) IN ('CAT','CATE','CATEGORY','CAT_NO','CAT_NUM','CAT_CODE','GROUP_NO','GRP','GROUP_CODE','GROUP_NAME','CAT_NAME','IDESC_CAT')
    OR UPPER(COLUMN_NAME) LIKE '%CAT%'
    OR UPPER(COLUMN_NAME) LIKE '%GROUP%'
    OR UPPER(TABLE_NAME) LIKE '%CAT%'
    OR UPPER(TABLE_NAME) LIKE '%GROUP%'
  )
ORDER BY OWNER, TABLE_NAME, COLUMN_ID;

-- 2) جداول مرشّحة لأسماء الفئات (غالباً جداول رئيسية)
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER IN ('MAS', 'ACCINV')
  AND (
       UPPER(TABLE_NAME) LIKE '%CAT%'
    OR UPPER(TABLE_NAME) LIKE '%GROUP%'
    OR UPPER(TABLE_NAME) IN ('ITEM_GROUP','ITEMGROUP','CATEGORIES','CATEGORY','CAT','MASCARD','GROUPS')
  )
ORDER BY OWNER, TABLE_NAME;

-- 3) عيّنة من جداول شائعة (جرّب واحداً واحداً — تجاهل إن لم يوجد)
-- SELECT * FROM MAS.ITEM_GROUP WHERE ROWNUM <= 30;
-- SELECT * FROM MAS.CATEGORY WHERE ROWNUM <= 30;
-- SELECT * FROM MAS.CAT WHERE ROWNUM <= 30;
-- SELECT * FROM MAS.GROUPS WHERE ROWNUM <= 30;

-- 4) الفئات المستخدمة فعلياً مع المواد في MASCARD
SELECT DISTINCT CAT, COUNT(*) AS CNT
FROM MAS.MASCARD
GROUP BY CAT
ORDER BY CAT;

-- 5) الفئات التي لها رصيد تشغيلات (BALANCE) — مثل Forms
SELECT DISTINCT CAT, COUNT(*) AS CNT
FROM MAS.BALANCE
WHERE STORE = 4
  AND NVL(QTY_OH, 0) > 0
GROUP BY CAT
ORDER BY CAT;

-- 6) فئة المادتين في الطلب CO022 (600018 و 200008)
SELECT 'MASCARD' AS SRC, TRIM(TO_CHAR(ITEM)) AS ITEM, TRIM(TO_CHAR(CAT)) AS CAT, IDESC
FROM MAS.MASCARD
WHERE TRIM(TO_CHAR(ITEM)) IN ('600018','200008')
   OR LTRIM(TRIM(TO_CHAR(ITEM)),'0') IN ('600018','200008');

SELECT 'BALANCE' AS SRC, TRIM(TO_CHAR(ITEM)) AS ITEM, TRIM(TO_CHAR(CAT)) AS CAT,
       TRIM(TO_CHAR(BATCH)) AS BATCH, QTY_OH
FROM MAS.BALANCE
WHERE STORE = 4
  AND NVL(QTY_OH,0) > 0
  AND (TRIM(TO_CHAR(ITEM)) IN ('600018','200008')
    OR LTRIM(TRIM(TO_CHAR(ITEM)),'0') IN ('600018','200008'))
ORDER BY ITEM, CAT, BATCH;

-- 7) إن وُجد جدول أسماء الفئات — ابحث عن أعمدة NAME + CAT
SELECT OWNER, TABLE_NAME, COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE OWNER IN ('MAS','ACCINV')
  AND UPPER(COLUMN_NAME) IN ('CAT','CAT_NO','CAT_NUM','GROUP_CODE','GROUP_NO')
  AND TABLE_NAME IN (
      SELECT TABLE_NAME FROM ALL_TAB_COLUMNS t2
      WHERE t2.OWNER = ALL_TAB_COLUMNS.OWNER
        AND UPPER(t2.COLUMN_NAME) IN ('NAME','NAME_A','NAME_AR','CAT_NAME','GROUP_NAME','IDESC','DESCR','DESCRIPTION')
  )
ORDER BY OWNER, TABLE_NAME;
