-- مقارنة معادلات INVREP050 للمندوب 39 / مستودع 4 / أيلول 2026
-- نفّذ في TOAD وأرسل نتيجة الاستعلامين

-- 1) تشخيص أعمدة الخصم/الضريبة
SELECT
  COUNT(*) AS LINE_CNT,
  COUNT(DISTINCT d.VYEAR || '-' || d.V_NUM) AS INV_CNT,
  ROUND(SUM(NVL(d.QTY,0)*NVL(d.SELL,0)), 3) AS GROSS_RAW,
  ROUND(SUM(NVL(d.DISC,0)), 6) AS DISC_SUM,
  ROUND(AVG(NVL(d.DISC,0)), 6) AS DISC_AVG,
  ROUND(MAX(NVL(d.DISC,0)), 6) AS DISC_MAX,
  ROUND(SUM(NVL(d.VOU_TAX,0)), 3) AS TAX_SUM,
  ROUND(SUM(NVL(d.QTY,0)*NVL(d.JD_COST,0)), 3) AS COST_AMT
FROM MAS.DAILY d
WHERE d.COMP_NUM = 1 AND d.TYPE = 9 AND d.STORE = 4
  AND d.VDATE >= DATE '2026-09-01' AND d.VDATE < DATE '2026-10-01'
  AND d.MAN_NUM = 39;

-- 2) أربع معادلات صافي جنبًا إلى جنب (MAN_NUM=39)
WITH inv AS (
  SELECT d.VYEAR, d.V_NUM,
         SUM(NVL(d.QTY,0)*NVL(d.SELL,0)) AS GROSS_RAW,
         SUM(NVL(d.QTY,0)*NVL(d.SELL,0)*(1-NVL(d.DISC,0))) AS GROSS_FRAC,
         SUM(NVL(d.QTY,0)*NVL(d.SELL,0)-NVL(d.DISC,0)) AS GROSS_AMT,
         MAX(NVL(d.VOU_DISC,0)) AS VOU_DISC,
         SUM(NVL(d.VOU_TAX,0)) AS TAX_SUM,
         SUM(NVL(d.QTY,0)*NVL(d.JD_COST,0)) AS COST_AMT
  FROM MAS.DAILY d
  WHERE d.COMP_NUM = 1 AND d.TYPE = 9 AND d.STORE = 4
    AND d.VDATE >= DATE '2026-09-01' AND d.VDATE < DATE '2026-10-01'
    AND d.MAN_NUM = 39
  GROUP BY d.VYEAR, d.V_NUM
)
SELECT
  COUNT(*) AS INV_CNT,
  ROUND(SUM(GROSS_RAW - VOU_DISC), 3) AS NET_RAW,
  ROUND(SUM(GROSS_FRAC - VOU_DISC), 3) AS NET_FRAC_DISC,
  ROUND(SUM(GROSS_AMT - VOU_DISC), 3) AS NET_AMT_DISC,
  ROUND(SUM(GROSS_RAW - VOU_DISC - TAX_SUM), 3) AS NET_RAW_MINUS_TAX,
  ROUND(SUM(COST_AMT), 3) AS COST_AMT
FROM inv;

-- الهدف Forms: NET=10213.988  COST=4801.379
