-- إيجاد تعبير يعطي فرق الصافي 767.484 وفرق التكلفة 51.859
-- (Forms 10213.988 / 4801.379 مقابل QTY*SELL-VOU_DISC / QTY*JD_COST)

WITH base AS (
  SELECT d.*,
         NVL(d.QTY,0) AS Q,
         NVL(d.BONUS,0) AS B,
         NVL(d.SELL,0) AS S,
         NVL(d.JD_COST,0) AS C,
         NVL(d.DISC,0) AS DC,
         NVL(d.VOU_TAX,0) AS TX,
         NVL(d.VOU_DISC,0) AS VD
  FROM MAS.DAILY d
  WHERE d.COMP_NUM = 1 AND d.TYPE = 9 AND d.STORE = 4
    AND d.VDATE >= DATE '2026-09-01' AND d.VDATE < DATE '2026-10-01'
    AND d.MAN_NUM = 39
)
SELECT
  ROUND(SUM(Q*S), 3) AS GROSS,
  ROUND(SUM(B*S), 3) AS BONUS_SELL,
  ROUND(SUM(B*C), 3) AS BONUS_COST,
  ROUND(SUM(CASE WHEN Q = 0 AND B > 0 THEN B*S ELSE 0 END), 3) AS PURE_BONUS_SELL,
  ROUND(SUM(CASE WHEN Q = 0 AND B > 0 THEN B*C ELSE 0 END), 3) AS PURE_BONUS_COST,
  ROUND(SUM(CASE WHEN B > 0 THEN Q*S ELSE 0 END), 3) AS SELL_ON_BONUS_LINES,
  ROUND(SUM(CASE WHEN B > 0 THEN Q*C ELSE 0 END), 3) AS COST_ON_BONUS_LINES,
  ROUND(SUM(CASE WHEN B > 0 THEN B*S ELSE 0 END), 3) AS BONUS_SELL_WHEN_B,
  ROUND(SUM(Q*S) - SUM(B*S), 3) AS GROSS_MINUS_BONUS_SELL,
  ROUND(SUM((Q+B)*C) - SUM(Q*C), 3) AS EXTRA_COST_IF_QTY_PLUS_BONUS,
  ROUND(SUM(TX), 3) AS TAX,
  COUNT(*) AS LINES,
  SUM(B) AS BONUS_QTY_SUM,
  SUM(Q) AS QTY_SUM
FROM base;

-- مرتجعات TYPE 10/11 لنفس المندوب/الفترة
SELECT TYPE,
       COUNT(*) CNT,
       ROUND(SUM(NVL(QTY,0)*NVL(SELL,0)), 3) AS GROSS,
       ROUND(SUM(NVL(QTY,0)*NVL(JD_COST,0)), 3) AS COST_AMT,
       ROUND(SUM(NVL(BONUS,0)*NVL(SELL,0)), 3) AS BONUS_SELL
FROM MAS.DAILY
WHERE COMP_NUM = 1 AND STORE = 4 AND TYPE IN (10, 11)
  AND VDATE >= DATE '2026-09-01' AND VDATE < DATE '2026-10-01'
  AND MAN_NUM = 39
GROUP BY TYPE;

-- مقارنة MAN_NUM = 29 (إن كان إبراهيم = 29 في Forms)
WITH inv AS (
  SELECT VYEAR, V_NUM,
         SUM(NVL(QTY,0)*NVL(SELL,0)) AS GROSS,
         MAX(NVL(VOU_DISC,0)) AS VOU_DISC,
         SUM(NVL(QTY,0)*NVL(JD_COST,0)) AS COST_AMT
  FROM MAS.DAILY
  WHERE COMP_NUM = 1 AND TYPE = 9 AND STORE = 4
    AND VDATE >= DATE '2026-09-01' AND VDATE < DATE '2026-10-01'
    AND MAN_NUM = 29
  GROUP BY VYEAR, V_NUM
)
SELECT COUNT(*) INV_CNT,
       ROUND(SUM(GROSS - VOU_DISC), 3) AS NET_AMT,
       ROUND(SUM(COST_AMT), 3) AS COST_AMT
FROM inv;
