-- ============================================================
-- Toad: اكتشاف أسماء الفئات العربية (CAT) في Oracle
-- نفّذ كل قسم على حدة
-- ============================================================

-- أ) جداول فيها عمود CAT + عمود اسم/وصف
SELECT a.OWNER, a.TABLE_NAME,
       a.COLUMN_NAME AS CAT_COL,
       b.COLUMN_NAME AS NAME_COL,
       b.DATA_TYPE
FROM ALL_TAB_COLUMNS a
JOIN ALL_TAB_COLUMNS b
  ON b.OWNER = a.OWNER AND b.TABLE_NAME = a.TABLE_NAME
WHERE a.OWNER IN ('MAS','ACCINV','SYSTEM')
  AND UPPER(a.COLUMN_NAME) IN ('CAT','CATE','CATEGORY','CAT_NO','CAT_NUM','CAT_CODE','GROUP_NO','GROUP_CODE')
  AND UPPER(b.COLUMN_NAME) IN (
      'NAME','NAME_A','NAME_AR','NAME_E','ENAME','ANAME',
      'CAT_NAME','CAT_ANAME','CAT_ENAME','CNAME','CDESC','DESCR','DESCRIPTION',
      'IDESC','GROUP_NAME','GROUP_ENAME','TITLE','TITLE_A','A_NAME','E_NAME',
      'TAK_NAME','TAK_ENAME','MEANING','LOOKUP_MEANING'
  )
ORDER BY a.OWNER, a.TABLE_NAME;

-- ب) جداول اسمها يشبه فئة/ثابت/قائمة
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER IN ('MAS','ACCINV')
  AND (
       UPPER(TABLE_NAME) LIKE '%CAT%'
    OR UPPER(TABLE_NAME) LIKE '%GROUP%'
    OR UPPER(TABLE_NAME) LIKE '%TYPE%'
    OR UPPER(TABLE_NAME) LIKE '%LOOK%'
    OR UPPER(TABLE_NAME) LIKE '%CODE%'
    OR UPPER(TABLE_NAME) LIKE '%CONST%'
    OR UPPER(TABLE_NAME) LIKE '%STATIC%'
    OR UPPER(TABLE_NAME) LIKE '%REF%'
  )
ORDER BY OWNER, TABLE_NAME;

-- ج) عيّنة من مرشّحين شائعين (تجاهل إن فشل)
-- SELECT * FROM MAS.TYPES WHERE ROWNUM <= 40;
-- SELECT * FROM MAS.TYPE WHERE ROWNUM <= 40;
-- SELECT * FROM MAS.CODES WHERE ROWNUM <= 40;
-- SELECT * FROM MAS.CODE WHERE ROWNUM <= 40;
-- SELECT * FROM MAS.LOOKUP WHERE ROWNUM <= 40;
-- SELECT * FROM ACCINV.TYPES WHERE ROWNUM <= 40;

-- د) هل يوجد وصف للفئة داخل MASCARD؟
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER='MAS' AND TABLE_NAME='MASCARD'
ORDER BY COLUMN_ID;

-- هـ) كل CAT مع عدد المواد (للتحقق)
SELECT TRIM(TO_CHAR(CAT)) AS CAT, COUNT(*) AS CNT
FROM MAS.MASCARD
GROUP BY TRIM(TO_CHAR(CAT))
ORDER BY TO_NUMBER(REGEXP_REPLACE(TRIM(TO_CHAR(CAT)),'[^0-9]',''));
